- block:
    - name: APT | Install DotDeb key
      apt_key: 
        url: "https://www.dotdeb.org/dotdeb.gpg"
        state: present

    - name: APT | Add Dotdeb repository
      apt_repository:
        repo: "deb http://packages.dotdeb.org jessie all"
        filename: dotdeb
        state: present

  when: ansible_distribution_release == "jessie"

- name: Install PHP 7
  apt: pkg="{{ item }}"
  with_items:
    - php
    - php7.0
    - php7.0-cli
    - php7.0-fpm
    - php7.0-mysql
    - php7.0-curl
    - php7.0-json
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-memcached
    - php7.0-readline
    - php7.0-intl
    - php7.0-sqlite3
    - php7.0-gmp
    - php7.0-geoip
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip
